quarkus.banner.enabled=false
quarkus.log.level=WARN

# Native image config
quarkus.ssl.native=true
quarkus.native.auto-service-loader-registration=true
quarkus.native.resources.includes=images/*.yaml,tools/*.yaml,git-remote-isx,dev/tamboui/tui/bindings/*.properties
quarkus.native.additional-build-args=--initialize-at-run-time=dev.incusspawn.Environment\\,dev.incusspawn.RuntimeServices\\,dev.tamboui.tui\\,dev.tamboui.toolkit\\,dev.tamboui.terminal\\,dev.tamboui.capability\\,dev.tamboui.error\\,dev.tamboui.widget\\,dev.tamboui.backend.panama,\
  -H:+ForeignAPISupport,-H:+SharedArenaSupport,--enable-native-access=ALL-UNNAMED,\
  -Os,--gc=serial,\
  --initialize-at-build-time=dev.tamboui.backend.panama.unix.PlatformConstants
