package dev.incusspawn.config;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;

/**
 * Collects {@link EnvEntry} declarations from templates and tools, validates
 * consistency, and generates the shell script for {@code /etc/profile.d/isx-env.sh}.
 *
 * <h3>Conflict rules</h3>
 * <ul>
 *   <li>{@code set + set}, same value → OK (idempotent)</li>
 *   <li>{@code set + set}, different value → build error</li>
 *   <li>{@code set + set-if-unset} → {@code set} wins</li>
 *   <li>{@code set-if-unset + set-if-unset}, different value → first wins</li>
 *   <li>{@code prepend / append} → always accumulated</li>
 *   <li>{@code set + prepend/append} → OK: base then modify</li>
 *   <li>Raw entries → appended verbatim, no conflict detection</li>
 * </ul>
 *
 * Shell output uses one export line per operation so that each prepend/append
 * reads the current runtime value:
 * <pre>
 * export VAR="base"
 * export VAR="pre-A${VAR:+ $VAR}"
 * export VAR="${VAR:+$VAR }suf-A"
 * </pre>
 */
public class EnvResolver {

    record SourcedEntry(EnvEntry entry, String source) {}

    private final List<SourcedEntry> entries = new ArrayList<>();

    public void addAll(List<EnvEntry> envEntries, String source) {
        for (var entry : envEntries) {
            entries.add(new SourcedEntry(entry, source));
        }
    }

    public void add(EnvEntry entry, String source) {
        entries.add(new SourcedEntry(entry, source));
    }

    /**
     * Resolve all collected entries and generate the profile.d script content.
     *
     * @throws EnvConflictException if two {@code set} entries declare different
     *     values for the same variable
     */
    public String resolve() {
        var structured = new LinkedHashMap<String, VarState>();
        var rawLines = new ArrayList<String>();

        for (var sourced : entries) {
            var entry = sourced.entry();
            if (entry.isRaw()) {
                rawLines.add(entry.getRaw());
                continue;
            }

            var state = structured.computeIfAbsent(entry.getName(), k -> new VarState());

            switch (entry.getStrategy()) {
                case SET -> {
                    if (state.base != null && state.base.entry().getStrategy() == EnvEntry.Strategy.SET) {
                        if (!state.base.entry().getValue().equals(entry.getValue())) {
                            throw new EnvConflictException(entry.getName(),
                                    state.base.entry().getValue(), state.base.source(),
                                    entry.getValue(), sourced.source());
                        }
                    } else {
                        state.base = sourced;
                    }
                }
                case SET_IF_UNSET -> {
                    if (state.base == null) {
                        state.base = sourced;
                    }
                }
                case PREPEND -> state.prepends.add(sourced);
                case APPEND -> state.appends.add(sourced);
            }
        }

        var sb = new StringBuilder();
        sb.append("# Generated by incus-spawn — do not edit\n");

        for (var entry : structured.entrySet()) {
            var name = entry.getKey();
            var state = entry.getValue();
            generateLines(sb, name, state);
        }

        for (var raw : rawLines) {
            sb.append(raw).append('\n');
        }

        return sb.toString();
    }

    private static void generateLines(StringBuilder sb, String name, VarState state) {
        if (state.base != null) {
            var baseEntry = state.base.entry();
            switch (baseEntry.getStrategy()) {
                case SET -> sb.append("export ").append(name).append('=')
                        .append(shellQuote(baseEntry.getValue())).append('\n');
                case SET_IF_UNSET -> sb.append("export ").append(name).append("=\"${")
                        .append(name).append(":-")
                        .append(shellEscape(baseEntry.getValue())).append("}\"\n");
                default -> {}
            }
        }

        for (var prepend : state.prepends) {
            var entry = prepend.entry();
            var sep = entry.getSeparator();
            sb.append("export ").append(name).append("=\"")
                    .append(shellEscape(entry.getValue()))
                    .append("${").append(name).append(":+")
                    .append(shellEscape(sep))
                    .append("$").append(name).append("}\"\n");
        }

        for (var append : state.appends) {
            var entry = append.entry();
            var sep = entry.getSeparator();
            sb.append("export ").append(name).append("=\"${")
                    .append(name).append(":+$").append(name)
                    .append(shellEscape(sep)).append("}")
                    .append(shellEscape(entry.getValue())).append("\"\n");
        }
    }

    static String shellQuote(String value) {
        return "\"" + shellEscape(value) + "\"";
    }

    static String shellEscape(String value) {
        var sb = new StringBuilder(value.length());
        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);
            switch (c) {
                case '\\' -> sb.append("\\\\");
                case '"'  -> sb.append("\\\"");
                case '$'  -> sb.append("\\$");
                case '`'  -> sb.append("\\`");
                case '\n', '\r' -> throw new IllegalArgumentException(
                        "Env var value must not contain newline or carriage return characters");
                default   -> sb.append(c);
            }
        }
        return sb.toString();
    }

    private static class VarState {
        SourcedEntry base;
        final List<SourcedEntry> prepends = new ArrayList<>();
        final List<SourcedEntry> appends = new ArrayList<>();
    }

    public static class EnvConflictException extends RuntimeException {
        public EnvConflictException(String varName, String value1, String source1,
                                     String value2, String source2) {
            super("Conflicting environment variable '" + varName + "':\n"
                    + "  " + source1 + " sets it to: " + value1 + "\n"
                    + "  " + source2 + " sets it to: " + value2);
        }
    }
}
